[package]
name = "tire"
version = "0.1.0"
edition = "2024"
license = "MIT - OSI approved"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4.27"
reqwest = { version = "0.12.20", features = ["blocking"] }
thiserror = "2.0.12"
toml = "0.8.23"
