[tool.mypy]
enable_error_code = "ignore-without-code, possibly-undefined"
explicit_package_bases = true
mypy_path = ["src"]
namespace_packages = true
pretty = false
python_version = "${TIRE_MIN_PYTHON_VERSION}"
show_error_codes = true
show_error_context = true
strict = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
verbosity_test_cases = 1
verbosity_assertions = 2
console_output_style = "count"
log_cli_level = "info"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.isort]
forced-separate = ["test", "tests", "testing", "testsuite"]
